// gen-math-vectors.go writes corpus/natives/math-vectors.tsv: math.Exp,
// math.Pow and math.Sqrt as Go computes them on GOARCH=wasm, which is what
// lg's js/wasm build (the shipping xsofy) computes and what rt/wasm/math.lg
// ports: the portable algorithms, no FMA, no arch Exp. Native lg on arm64
// can differ in the last place (exp_arm64.s and compiler-fused x*y+z), so
// the test checks the port against this table exactly and against native
// lg within 1 ulp.
//
// Build and run from dev/lower-wasm (Go toolchain + wasmtime; nothing is
// installed, the binary goes to a temp dir):
//
//	d=$(mktemp -d) && GOOS=wasip1 GOARCH=wasm go build -o $d/m.wasm corpus/natives/gen-math-vectors.go &&
//	  wasmtime $d/m.wasm > corpus/natives/math-vectors.tsv
//
// Columns: op, a, b (float64 bits as signed decimal, b = 0 for unary ops),
// result bits. Inputs come from a fixed xorshift stream plus edge cases.
package main

import (
	"fmt"
	"math"
)

var st uint64 = 0x9E3779B97F4A7C15

func next() uint64 { st ^= st << 13; st ^= st >> 7; st ^= st << 17; return st }

// uniform in [lo, hi)
func uni(lo, hi float64) float64 { return lo + (hi-lo)*float64(next()>>11)/(1<<53) }

func b(x float64) int64 { return int64(math.Float64bits(x)) }

func row(op string, x, y float64) {
	var r float64
	switch op {
	case "exp":
		r = math.Exp(x)
	case "sqrt":
		r = math.Sqrt(x)
	case "pow":
		r = math.Pow(x, y)
	}
	fmt.Printf("%s\t%d\t%d\t%d\n", op, b(x), b(y), b(r))
}

func main() {
	fmt.Println("# op\ta-bits\tb-bits\tresult-bits   (Go GOARCH=wasm math; generated by corpus/natives/gen-math-vectors.go)")
	edges := []float64{0, math.Copysign(0, -1), 1, -1, 0.5, 2, 1e-300, 5e-324, 2.2250738585072014e-308, 3.725290298461914e-09,
		-3.725290298461914e-09, 709.782712893384, 709.79, -745.1332191019411, -745.14, -708.4, 100, -100, 1e308,
		math.Inf(1), math.Inf(-1), math.NaN()}
	for _, x := range edges {
		row("exp", x, 0)
		row("sqrt", x, 0)
	}
	for i := 0; i < 400; i++ {
		row("exp", uni(-50, 50), 0)
	}
	for i := 0; i < 60; i++ {
		row("exp", uni(-745, 709), 0)
	}
	for i := 0; i < 100; i++ {
		row("sqrt", math.Float64frombits(next()&^(1<<63)), 0) // any positive bit pattern, subnormals and NaNs included
	}
	pe := []float64{0, math.Copysign(0, -1), 1, -1, 2, -2, 0.5, -0.5, 3, -3, 1.5, -1.5, 1e10, 1e300, 1e-300, 5e-324,
		math.Inf(1), math.Inf(-1), math.NaN(), 9.3e18, -9.3e18}
	for _, x := range pe {
		for _, y := range pe {
			row("pow", x, y)
		}
	}
	for i := 0; i < 400; i++ {
		row("pow", uni(0.01, 10), uni(-20, 20))
	}
	for i := 0; i < 100; i++ {
		row("pow", uni(-10, 10), float64(int64(uni(-60, 60))))
	}
}
